project_id = "ofhejtwaigiqyejbvncz"

[functions.send-invitation-email]
verify_jwt = true

[functions.news-sitemap]
verify_jwt = false

[functions.generate-article-fields]
verify_jwt = false

[functions.pxweb-connector]
verify_jwt = false

[functions.cpi-ingest]
verify_jwt = false
